analyze_cell_polarity_results('../results/Addback/01/')
analyze_cell_polarity_results('../results/Addback/02/')
analyze_cell_polarity_results('../results/Addback/03/')
analyze_cell_polarity_results('../results/Addback/04/')
analyze_cell_polarity_results('../results/Addback/05/')
analyze_cell_polarity_results('../results/Addback/06/')

analyze_cell_polarity_results('../results/LKB_null/01/')
analyze_cell_polarity_results('../results/LKB_null/02/')
analyze_cell_polarity_results('../results/LKB_null/03/')
analyze_cell_polarity_results('../results/LKB_null/04/')
analyze_cell_polarity_results('../results/LKB_null/05/')